
spring:
  application:
    name: spring-cloud-vsl-ba-consumer
server:
  port: 8090
  context-path: /consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
